# Generated by Django 3.2.13 on 2022-04-25 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visiter',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='visiters', serialize=False, to='users.user')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('second_name', models.CharField(blank=True, max_length=30, null=True)),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Адрес')),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
